templates/protocols/http/basic-http.mdx, templates/protocols/http/http-payloads.mdx
https://github.com/projectdiscovery/nuclei/pull/4292
=> session reuse is enabled as default

tools/nuclei/running.mdx
From https://github.com/projectdiscovery/nuclei/pull/4328
=> Added note for template list

templates/protocols/http/http-payloads-examples.mdx
Closes https://github.com/projectdiscovery/nuclei/issues/4619
=> Fix multiple-raw-example template

mint.json, tools/cvemap/install.mdx, tools/cvemap/overview.mdx, tools/cvemap/running.mdx, tools/cvemap/usage.mdx, tools/index.mdx
Content for cvemap
- Updating mint file (nav)
- Adding pages for cvemap
=> Cvemap Content

mint.json, tools/nuclei/mass-scanning-cli.mdx
=> nuclei mass scanning documentation

mint.json, tools/nuclei/mass-scanning-cli.mdx, tools/nuclei/nuclei-sdk.mdx, tools/nuclei/running.mdx
- continuation of https://github.com/projectdiscovery/docs/pull/23
- adds docs on nuclei sdk and reporting issues related to nuclei sdk usage
=> added docs for nuclei sdk

mint.json, tools/nuclei/authenticated-scans.mdx, tools/nuclei/overview.mdx
- Nuclei v3.2.0: Authenticated Scans and Format
=> feat: authentication scans docs

tools/subfinder/install.mdx
docs for https://github.com/projectdiscovery/subfinder/pull/1212
=> update zoomeyeapi rel doc

tools/subfinder/install.mdx
=> fix cmd instruction

.github/workflows/build-js-helper-docs.yaml, mint.json, static/docsbuilder/generate.sh, static/docsbuilder/update-js-helpers.sh, templates/reference/js-helper-functions.mdx
- weekly autogenerated documentation for javascript helper functions
- code protocol helper functions (https://github.com/projectdiscovery/nuclei/pull/4966 )
=> js helper function docs

tools/nuclei/running.mdx
Ref: https://discord.com/channels/695645237418131507/1273282931997151384
=> docs(nuclei): add notes for template allow/deny list

templates/protocols/headless-examples.mdx, templates/protocols/headless.mdx
Satisfy https://github.com/projectdiscovery/nuclei/pull/5545
=> docs(headless): add `waitdialog` action

api-reference/asset/get-exposure-metrics.mdx, api-reference/assets/get-asset-screenshot.mdx, api-reference/configurations/get-verify-config-contents.mdx, api-reference/enumerations/delete-assets-in-bulk.mdx, api-reference/enumerations/export-enumeration-of-user.mdx, api-reference/enumerations/get-all-enumeration-contents.mdx, api-reference/enumerations/get-all-enumeration-stats.mdx, api-reference/enumerations/get-enumeration-config.mdx, api-reference/enumerations/group-assets-by-filters-for-an-enumeration.mdx, api-reference/enumerations/group-assets-by-filters.mdx, api-reference/export/export-filtered-scan-results.mdx, api-reference/export/get-export-list-for-user.mdx, api-reference/get-audit-logs-for-team.mdx, api-reference/scans/delete-scan-in-bulk.mdx, api-reference/scans/delete-vulns-tracker-association.mdx, api-reference/update-enumeration-config.mdx, api-reference/usage/get-api-services-usage.mdx, api-reference/users/get-tunnels-list.mdx, api-reference/users/update-current-subscription.mdx, mint.json, openapi.yaml
=> docs update (add x-team-id) header and missing endpoints

templates/protocols/headless.mdx
Satisfy https://github.com/projectdiscovery/nuclei/issues/5631
=> docs(templates): add std page lifecycle actions

tools/nuclei/running.mdx
- Add documentation for MongoDB reporting
=> Add MongoDB Reporting Documentation

cloud/features.mdx, cloud/introduction.mdx
Made changes to the introduction page to more closely align to our positioning. Also changed Features to be about Key Benefits and mostly targeted toward explaining how PDCP is different from open source.
Ideally I'd like to rename Features to Key Benefits, but I don't know how so maybe Sandeep you can help me there.
=> Updates to Introduction and Features in Cloud Platform docs

tools/nuclei/authenticated-scans.mdx
Discussed in [#4999](https://github.com/projectdiscovery/nuclei/issues/4999)
=> Update wrong documentation regarding variables in dynamic auth

tools/uncover/running.mdx, tools/uncover/usage.mdx
=> add `-asq` doc

tools/httpx/usage.mdx
=> update httpx doc for `-filter-duplicates` option

tools/pdtm/install.mdx
=> Fixed misspelling in install.mdx for pdtm

tools/interactsh/overview.mdx
=> Fix typo in interactsh overview page

templates/protocols/http/http-payloads.mdx
Closes https://github.com/projectdiscovery/nuclei/issues/6110
=> docs(http): add note on local file access for payloads

cloud/pricing.mdx
- keep request quote CTA
- update pricing page copy for Growth tier
- `git status --short`
=> Update pricing copy

tools/interactsh/running.mdx
=> interactsh - Fix typo in running doc

tools/nuclei/running.mdx
closes https://github.com/projectdiscovery/docs/issues/149. for the context: https://github.com/orgs/projectdiscovery/discussions/6248
=> update nuclei flags

tools/dnsx/running.mdx
closes https://github.com/projectdiscovery/docs/issues/152
=> add examples for resolver option
